In [1]:
# GP/A : 매출총이익 / 자산총계
# 매출총이익 : 매출액 - 매출원가
# 자산총계 : 자기자본 + 부채
# PBR(주가순자산비율) : 현재주가 / BPS
# BPS(주당순자산가치) : 기업의 순자산 / 총 발행 주식 수

import pandas as pd
corp_info = pd.read_csv('corp.csv', header=0)

corp_info = corp_info[['종목코드','종목명','현재가','상장주식수']]
corp_info['종목코드'] = 'A' + corp_info['종목코드'].astype(str)

corp_result = pd.read_excel('SAMPLE_2018.xlsx')

corp_data = corp_result[['종목코드','매출총이익','자본총계','자산총계','부채총계']]

corp_total = pd.merge(corp_info, corp_data, how='left', on='종목코드')
corp_total_dropna = corp_total.dropna()
corp_total_dropna

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계
0,A005930,삼성전자,"55,400","5,969,782,550",1.113770e+14,2.477532e+14,3.393572e+14,9.160407e+13
1,A207940,삼성바이오로직스,"794,000","66,165,000",1.451599e+11,4.155468e+12,5.980409e+12,1.824940e+12
2,A000660,SK하이닉스,"71,800","728,002,365",2.526423e+13,4.685233e+13,6.365834e+13,1.680600e+13
3,A035420,NAVER,"305,500","164,263,395",5.586905e+12,5.949141e+12,9.881191e+12,3.932050e+12
4,A051910,LG화학,"667,000","70,592,343",5.346197e+12,1.732213e+13,2.894414e+13,1.162201e+13
...,...,...,...,...,...,...,...,...
2426,A114570,지스마트글로벌,620,"11,339,394",1.130118e+10,1.103738e+11,1.535438e+11,4.316996e+10
2429,A310870,한국제8호스팩,"2,020","3,420,000",0.000000e+00,6.350131e+09,6.879631e+09,5.295000e+08
2432,A121890,에스디시스템,739,"9,047,578",4.205643e+09,1.675393e+10,3.475391e+10,1.799999e+10
2434,A080440,에스제이케이,498,"13,325,960",1.897520e+08,1.306286e+10,5.962112e+10,4.655827e+10
2447,A158310,스타모빌리티,505,"12,071,642",1.729789e+09,2.001856e+10,4.418349e+10,2.416494e+10

In [2]:
corp_total["GP/A"] = corp_total["매출총이익"]/corp_total["자본총계"]
corp_total["BPS"] = corp_total["자본총계"]/corp_total['상장주식수'].str.replace(",","").astype("float64")
corp_total["PBR"] = corp_total["현재가"].str.replace(',','').astype("float64")/corp_total["BPS"].astype("float64")
corp_total = corp_total[pd.notnull(corp_total['PBR']) | pd.notnull(corp_total['GP/A'])]
corp_total["GP/A Rank"] = corp_total["GP/A"].rank()
corp_total["PBR Rank"] = corp_total["PBR"].rank(ascending=0)
corp_total["Total Rank"] = corp_total["GP/A Rank"] + corp_total["PBR Rank"]
corp_total.sort_values(by=['Total Rank'], ascending=0)[:20]

,종목코드,종목명,현재가,상장주식수,매출총이익,자본총계,자산총계,부채총계,GP/A,BPS,PBR,GP/A Rank,PBR Rank,Total Rank
2094,A069640,한세엠케이,"2,625","12,909,322",1.916986e+11,1.485118e+11,2.056286e+11,5.711690e+10,1.290797,11504.225396,0.228177,1904.0,1902.0,3806.0
1021,A095570,AJ네트웍스,"2,960","46,822,295",1.056691e+12,5.082648e+11,2.575139e+12,2.066875e+12,2.079017,10855.188559,0.272681,1939.0,1863.0,3802.0
1211,A005990,매일홀딩스,"7,830","13,718,304",4.548671e+11,5.160672e+11,8.489405e+11,3.328733e+11,0.881411,37618.876721,0.208140,1835.0,1924.0,3759.0
904,A016450,한세예스24홀딩스,"4,095","40,000,000",6.379932e+11,6.177373e+11,1.678316e+12,1.060579e+12,1.032791,15443.432350,0.265161,1869.0,1871.0,3740.0
564,A037560,LG헬로비전,"3,820","77,446,865",1.061144e+12,1.059260e+12,1.935139e+12,8.758786e+11,1.001779,13677.249221,0.279296,1866.0,1857.0,3723.0
695,A006840,AK홀딩스,"16,800","13,247,561",1.045615e+12,1.473898e+12,3.397931e+12,1.924034e+12,0.709422,111258.037687,0.151000,1761.0,1958.0,3719.0
99,A001040,CJ,"82,000","29,176,998",8.353219e+12,1.252181e+13,3.172955e+13,1.920774e+13,0.667094,429167.190024,0.191068,1730.0,1938.0,3668.0
2331,A194510,파티게임즈,536,"24,488,350",4.225842e+10,6.304665e+10,1.779223e+11,1.148757e+11,0.670272,2574.556799,0.208191,1734.0,1923.0,3657.0
2158,A084870,TBH글로벌,"1,420","20,856,819",1.165821e+11,1.834459e+11,2.662459e+11,8.279998e+10,0.635512,8795.487126,0.161446,1706.0,1951.0,3657.0
1066,A005740,크라운해태홀딩스,"8,650","14,847,347",3.690811e+11,4.936934e+11,1.286505e+12,7.928112e+11,0.747592,33251.288463,0.260140,1779.0,1873.0,3652.0
114,A023530,롯데쇼핑,"75,800","28,288,755",7.507670e+12,1.242737e+13,2.625931e+13,1.383194e+13,0.604124,439304.340718,0.172546,1688.0,1948.0,3636.0
470,A093050,LF,"12,750","29,240,000",9.428273e+11,1.183429e+12,1.651841e+12,4.684124e+11,0.796691,40472.931019,0.315025,1805.0,1818.0,3623.0
478,A084690,대상홀딩스,"10,200","36,212,538",8.912242e+11,1.094780e+12,2.629589e+12,1.534809e+12,0.814067,30232.062608,0.337390,1813.0,1791.0,3604.0
40,A030200,KT,"23,650","261,111,808",2.346014e+13,1.473128e+13,3.218883e+13,1.745755e+13,1.592539,56417.517510,0.419196,1926.0,1675.0,3601.0
1615,A002880,대유에이텍,631,"106,915,987",1.673957e+11,1.703368e+11,8.895806e+11,7.192438e+11,0.982734,1593.183403,0.396062,1861.0,1715.0,3576.0
1533,A058860,KTis,"2,135","34,802,000",4.508260e+11,1.602497e+11,2.292460e+11,6.899632e+10,2.813272,4604.612752,0.463665,1945.0,1615.0,3560.0
1546,A016090,대현,"1,660","44,282,310",1.621296e+11,1.856395e+11,2.589715e+11,7.333198e+10,0.873357,4192.182341,0.395975,1834.0,1716.0,3550.0
1483,A058850,KTcs,"1,860","42,685,000",1.016085e+12,1.617186e+11,3.502797e+11,1.885610e+11,6.283044,3788.652267,0.490940,1955.0,1582.0,3537.0
2119,A026040,제이에스티나,"1,945","16,503,790",8.425222e+10,7.144697e+10,1.152422e+11,4.379525e+10,1.179227,4329.125249,0.449282,1891.0,1632.0,3523.0
279,A000150,두산,"41,750","16,523,835",3.323509e+12,7.145046e+12,2.888028e+13,2.173524e+13,0.465149,432408.468797,0.096552,1539.0,1969.0,3508.0